### ISSUE TITLE
Use json settings file over xml

### ISSUE THREAD

**Issue by millo-k** [menees/Analyzers#2]
Would it not make sense to use a `json` file to configure the settings as [StyleCop](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md) does. The validation of the `xml` schema via an additional `xsd` file seems cumbersome for the consumer.

**Comment by menees** [comment]
I'm aware of StyleCop's usage of JSON, and I'm aware that they pull in the whole [LightJson](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/tree/master/StyleCop.Analyzers/StyleCop.Analyzers/LightJson) source code to parse it. I prefer XML for documents such as settings files, and I prefer the built-in System.Xml.Linq API for it. I don't want to add a dependency on Newtonsoft.Json, System.Text.Json, or some other JSON parser when XML is available and well-suited to the task. I don't share the opinion that I should make things use JSON just because it's popular when it wouldn't solve the business requirement significantly better. Settings files are rarely edited anyway. Converting to use JSON would have a cost that wouldn't be justified. I frequently think about Eric Gunnerson's 2004 article, [Minus 100 Points](https://web.archive.org/web/20100709172807/http://blogs.msdn.com/b/ericgu/archive/2004/01/12/57985.aspx).
