### ISSUE TITLE
Support commented out code ie //// … to skip MEN002

### ISSUE THREAD

**Issue by gaurav137** [menees/Analyzers#8]
Commenting out blocks of code during development cycle ends up at times crossing the max line length limit set for MEN002. It would be great if a comment with four slashes ie //// can be ignored by this rule. This would be similar to https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1626.md which also allows for the same by differentiating normal code from commented code based on four slashes: “ 
When commenting out lines of code, it is advisable to begin the comment with four slashes to differentiate it from normal comments”. 

Right now it gets painful to have to suppress this rule in code when commenting code shifts right and then remembering to remove suppression when uncommenting fixes the indentation to be within limits.

**Comment by menees** [comment]
I've added optional support for this in v3.0.9. It's off by default, but you can enable it by setting AllowLongFourSlashCommentLines = true in Menees.Analyzers.Settings.xml.

It's off by default because I don't like commented out blocks of code, and I don't want to allow them to bypass any of my analyzer rules. I remove code instead of commenting it out, and I use source control to get back the old code if I ever need it again. I'm a fan of rules like [Code Cracker's CC0037](https://code-cracker.github.io/diagnostics/CC0037.html) that require commented out code to be removed.

**Comment by gaurav137** [comment]
We also avoid commented code from being checked in. This setting is helping in quickly commenting out blocks and doing F5 while debugging w/o worrying about going over the col limit due to such temporary changes.
